apiVersion: v2
name: microservices-umbrella
description: Umbrella Helm chart to deploy all microservices and Kong configuration
type: application
version: 0.1.0
appVersion: "1.0.0" # Represents the overall application version

# Define dependencies (subcharts)
dependencies:
  - name: user-service
    version: "0.1.0" # Must match the version in helm/user-service/Chart.yaml
    repository: "file://../user-service" # Path relative to this Chart.yaml
    # condition: user-service.enabled # Optional: deploy conditionally

  - name: product-service
    version: "0.1.0"
    repository: "file://../product-service"
    # condition: product-service.enabled

  - name: order-service
    version: "0.1.0"
    repository: "file://../order-service"
    # condition: order-service.enabled

  - name: kong-config
    version: "0.1.0"
    repository: "file://../kong-config"
    # condition: kong-config.enabled