
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "user-service.serviceAccountName" . }} # Helper để tạo tên KSA
  namespace: {{ .Release.Namespace }} # Namespace hiện tại của release
  labels:
    {{- include "user-service.labels" . | nindent 4 }} # Helper cho labels chung
  {{- /* --- Xử lý Annotations --- */}}
  {{- /* Ưu tiên gcpServiceAccountEmail cục bộ, sau đó đến global */}}
  {{- $gsaEmail := .Values.serviceAccount.gcpServiceAccountEmail | default .Values.global.podGcpServiceAccountEmail -}}
  {{- /* Lấy các annotations tùy chỉnh từ values, đảm bảo nó là một dictionary */}}
  {{- $customAnnotations := .Values.serviceAccount.annotations | default dict -}}

  {{- /* Chỉ tạo khối 'annotations:' nếu có GSA email hoặc có custom annotations */}}
  {{- if or $gsaEmail (not (empty $customAnnotations)) }}
  annotations:
    {{- if $gsaEmail }}
    iam.gke.io/gcp-service-account: {{ $gsaEmail }}
    {{- end }}
    {{- /* Thêm các annotations tùy chỉnh khác (nếu có) */}}
    {{- range $key, $value := $customAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- /* --- Xử lý automountServiceAccountToken --- */}}
{{- /* Chỉ render nếu giá trị được cung cấp và là kiểu boolean */}}
{{- $autoMountToken := .Values.serviceAccount.automountServiceAccountToken -}}
{{- if kindIs "bool" $autoMountToken }}
automountServiceAccountToken: {{ $autoMountToken }}
{{- /* Nếu muốn có default khi không set:
else if eq $autoMountToken nil }}
automountServiceAccountToken: true
*/}}
{{- end }}
{{- end -}}
